"""Add contact to RequestPost

Revision ID: 123a810dcd0b
Revises: dea06f338052
Create Date: 2024-11-12 12:06:13.924681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123a810dcd0b'
down_revision = 'dea06f338052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_post', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
