"""Add author to DemandPost

Revision ID: 13c511b7d3c0
Revises: c26d40e6f0be
Create Date: 2024-11-10 23:07:11.798847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c511b7d3c0'
down_revision = 'c26d40e6f0be'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('demand_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=20), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_post', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
