"""Add contact column to request_post and service_post

Revision ID: 6993f7e35317
Revises: 123a810dcd0b
Create Date: 2024-11-12 21:35:47.417267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6993f7e35317'
down_revision = '123a810dcd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=False, server_default='N/A'))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               nullable=False)

    with op.batch_alter_table('service_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=False, server_default='N/A'))
    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_post', schema=None) as batch_op:
        batch_op.drop_column('contact')

    with op.batch_alter_table('request_post', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
