"""Add subject, university, and semester fields to ServicePost

Revision ID: 8dfe9325b9cb
Revises: 
Create Date: 2024-11-10 18:03:32.973228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfe9325b9cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('university', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('semester', sa.String(length=50), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('semester')
        batch_op.drop_column('university')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
