"""Add price and additional_information to RequestPost

Revision ID: dea06f338052
Revises: 8e93384a663f
Create Date: 2024-11-12 11:54:43.108955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea06f338052'
down_revision = '8e93384a663f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('additional_information', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_post', schema=None) as batch_op:
        batch_op.drop_column('additional_information')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
